[package]
name = "seno"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
description = "A fast Progress Bar Placeholder Tool"
repository = "https://github.com/EdwardJoke/seno"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
